"""English promo guideline entries for Word doc export (see generate_agent_rules_hebrew_docx.py)."""

from __future__ import annotations

from typing import TypedDict

from promo_guidelines_catalog import CATALOG_BY_NAME


class PromoGuideline(TypedDict):
    category: str
    name: str
    times: str
    duration: str
    lane: str
    cant_with: str
    variants: str
    extra: str
    examples: list[str]


CATEGORY_ORDER: tuple[str, ...] = (
    "Purchase & offers",
    "Core & gameplay",
    "Gems & amplifiers",
    "Dice",
    "Clan-Dash & ADS",
    "Seasonal & album",
    "Events, Lotto & Happy Hour",
    "Other / platform",
)


def _e(*lines: str) -> list[str]:
    return list(lines)


GUIDELINES: list[PromoGuideline] = [
    {
        "category": "Purchase & offers",
        "name": "Daily Deal (DD)",
        "times": "Every day (HARD). Sometimes Once + Multiple — August Monday: one merged row in description.",
        "duration": "Default: all day (Promo Time 11:00 UTC). Wild/Shiny Once → extra DD multiple same day.",
        "lane": "Offer · Mid/High/Max.",
        "cant_with": "Same pricing as second offer when both priced. DD BOGO needs LiveOps task config.",
        "variants": "Coins+Gems+central SKU; BOGO 2×/month; Wild/Shiny Once + alternate Multiple.",
        "extra": "Top PU driver (~30%). Weekly card bank (Nivi).",
        "examples": _e(
            "2026-04-01 — Daily Deal 4★ Reg + 2 Picks | H Pricing",
            "2026-04-03 — DD Shiny Limited + DD PAB (same day)",
            "2026-04-05 — DD Wild Ordinary ONCE | H price",
            "2026-08-05 — Daily Deal 100% SB + 8 Hammers | H Pricing",
            "2026-08-12 — Daily Deal 4★ Gold (on purchase) + Shield | High",
        ),
    },
    {
        "category": "Purchase & offers",
        "name": "RYD (Reveal Your Deal)",
        "times": "~6–10/month; rotate with Buy All / Decoy / Rolling.",
        "duration": "All day (11:00 UTC).",
        "lane": "Offer · High/Max.",
        "cant_with": "155% SB forbidden. Extreme days: no Wild hook; RDS→Extreme in all offers.",
        "variants": "Coins+Gems+hook+RDS+%SB; always prize beyond %SB.",
        "extra": "Different pricing tier than DD same day (HARD).",
        "examples": _e(
            "2026-04-03 — RYD 100% SB + Hammers Wheel",
            "2026-04-16 — RYD 100% SB + PAB",
            "2026-04-25 — Themed RYD 200% SB + Wild Gold",
            "2026-08-07 — RYD 3★ Reg + 100% SB | High Price",
            "2026-08-14 — RYD 4★ Gold + 100% SB | High Price",
        ),
    },
    {
        "category": "Purchase & offers",
        "name": "Buy All / Mystery Buy All",
        "times": "Buy All ~5–12/month; Mystery ~2–3/month.",
        "duration": "All day.",
        "lane": "Offer · High.",
        "cant_with": "Second deep coin VFM same day. Mystery: one prize per line in copy.",
        "variants": "Coins+RDS | Gems+GGS (+ prizes); Mystery = hidden reveal.",
        "extra": "Seasonal SKU = active Short Term.",
        "examples": _e(
            "2026-04-11 — Buy All SB wheel + 2 PAB",
            "2026-04-20 — Buy All Globez + Hammers",
            "2026-04-26 — Buy All AS Wheel + Quest Booster | H",
            "2026-08-10 — Buy All Coins+RDS+4★ Reg+2 Parasheep | Gems+GGS+3★ Gold+3000 Hero Coins",
            "2026-08-15 — Mystery Buy All (August plan)",
        ),
    },
    {
        "category": "Purchase & offers",
        "name": "Decoy Bonanza",
        "times": "Offer rotation; weekdays and sale days.",
        "duration": "All day.",
        "lane": "Offer · High/Max.",
        "cant_with": "Only one deep coin VFM per day.",
        "variants": "d1 Coins+RDS · d2 Gems+GGS decoy · d3 bundle.",
        "extra": "Creative usually Reuse.",
        "examples": _e(
            "2026-04-14 — Bonanza Offer M-H-H",
            "2026-04-23 — Decoy Bonanza",
            "2026-08-02 — Decoy d3: 5★ Reg + bundle | H",
            "2026-08-05 — Decoy d3: 4★ Gold + bundle | H",
            "2026-08-08 — Decoy d3: 3★ Gold + bundle | H",
        ),
    },
    {
        "category": "Purchase & offers",
        "name": "Rolling Offer — Buy X Get Y (BXGY)",
        "times": "~10–15 Rolling/month; 1/2/5/6 cycles.",
        "duration": "All day or timed window on board.",
        "lane": "Offer · M/High/Max.",
        "cant_with": "MFL same day; second hammer source; second deep VFM.",
        "variants": "6 denoms/cycle (Pay+1RDS+1GGS → SB → hook → Hammers → RDS → GGS). See mm_calendar/rolling_offer.md.",
        "extra": "Max 4 RDS + 2 GGS per cycle.",
        "examples": _e(
            "2026-04-07 — Rolling offer Buy 1 get 8 H - 04/07",
            "2026-04-16 — Rolling Offer - 2 cycles H price",
            "2026-05-15 — Rolling -15.05 supersized 5 cycles",
            "2026-07-01 — Rolling offer - 6 cycles Parasheep/AS",
            "2026-08-12 — Rolling Offer - 6 Cycles | M Pricing",
        ),
    },
    {
        "category": "Purchase & offers",
        "name": "Rolling Offer — Buy More for Less (BMFL)",
        "times": "Max 1/week + ~10-day cooldown; MFL anchors only.",
        "duration": "All day.",
        "lane": "Offer · High only (Aug 2026).",
        "cant_with": "Sale day; big BXGY; Mondays; second deep VFM.",
        "variants": "3 cycles: tiered Coins+Gems + %SB + Reg + Hammers + RDS + GGS.",
        "extra": "August builder: MFL anchor days only.",
        "examples": _e(
            "2026-04-02 — Rolling Offer Buy more for less H price 2026-04-02",
            "2026-06-17 — Rolling More for Less (hammers ladder)",
            "2026-07-05 — Buy more for less 2 Parasheep / 3 Parasheeps / AS",
            "2026-07-13 — Rolling more for less (PAB / Wild Any denoms)",
            "2026-08-03 — Rolling - Buy More for Less | H Pricing",
        ),
    },
    {
        "category": "Purchase & offers",
        "name": "Coin Sale",
        "times": "Fri+Sat weekends; major events.",
        "duration": "All day (11:00 UTC).",
        "lane": "Offer · sale depth.",
        "cant_with": "MGAP Matched/BOGO, MFL, Extreme (default), Price Cut, second VFM, Mondays.",
        "variants": "Segment % table (PU/IC/DPU/NPU).",
        "extra": "Pair with second VFM; stronger Core day after.",
        "examples": _e(
            "2026-05-05 — Coin Sale 100/125/200/555%",
            "2026-06-05 — Coin Sale up to 75%/100%",
            "2026-08-07 — Coin Sale Betty Boop 50/75/200/400%",
            "2026-08-08 — Coin Sale | High Pricing",
            "2026-08-14 — Coin Sale 50/75/200/500%",
        ),
    },
    {
        "category": "Purchase & offers",
        "name": "MGAP (BOGO / Bigger / Matched / Wild)",
        "times": "2/week; BOGO on 1st; ≥2 days between MGAP; not Mondays.",
        "duration": "≥12:00 UTC, usually 2h.",
        "lane": "Offer · High.",
        "cant_with": "MGAP+Bucks; BOGO on sale/last day; Matched on sale; second VFM.",
        "variants": "BOGO · Bigger · Matched · Wild Symbols.",
        "extra": "Revenue #1 (~29%).",
        "examples": _e(
            "2026-04-01 — MGAP BOGO",
            "2026-04-05 — MGAP Matched",
            "2026-04-16 — Extreme MGAP 200% SB",
            "2026-08-09 — MGAP BOGO",
            "2026-08-10 — MGAP BOGO (Monday board)",
        ),
    },
    {
        "category": "Purchase & offers",
        "name": "Piggy",
        "times": "Thursday anchor (may move).",
        "duration": "≥12:00 UTC, often 2h.",
        "lane": "Offer · High.",
        "cant_with": "Second deep VFM in same window.",
        "variants": "Break for <prize in title>; Gold allowed on break.",
        "extra": "Not second VFM.",
        "examples": _e(
            "2026-07-01 — Piggy for 5★ Reg",
            "2026-07-08 — Piggy for Shiny card",
            "2026-07-22 — Piggy break for 5 Hammers",
            "2026-08-05 — Piggy break for 3★ Reg",
            "2026-08-12 — Piggy break for 4★ Reg | High",
        ),
    },
    {
        "category": "Purchase & offers",
        "name": "Prize Mania",
        "times": "~every 1.5 weeks.",
        "duration": "Timed or all day.",
        "lane": "Offer · High.",
        "cant_with": "Mondays; amplifier overload.",
        "variants": "Wild Gold bundle vs standard coins+gems+RDS+GGS+SB.",
        "extra": "Monetization lane.",
        "examples": _e(
            "2026-05-03 — Prize Mania Wild Gold + Dice Booster 6H",
            "2026-05-22 — Prize Mania | H (Lucy's)",
            "2026-06-11 — Prize Mania Gems 4 RDS 1 GGS 5★ Gold 200% SB",
            "2026-08-06 — Prize Mania 3★ Gold pack | Coins, Gems",
            "2026-05-30 — Prize Mania | H Price",
        ),
    },
    {
        "category": "Purchase & offers",
        "name": "Counter PO",
        "times": "~2/month; on-top only.",
        "duration": "Timed / Night Plan.",
        "lane": "Offer · High.",
        "cant_with": "Must not replace DD or second VFM.",
        "variants": "FTD segmented topper.",
        "extra": "Pause DPU winback on sales.",
        "examples": _e(
            "2026-05-18 — Counter PO FTD segmented",
            "2026-06-22 — Counter PO on top",
            "2026-07-11 — Counter PO Night Plan variant",
            "2026-08-09 — Counter PO | Night Plan | High",
            "2026-04-28 — Counter PO segmented topper",
        ),
    },
    {
        "category": "Purchase & offers",
        "name": "Golden Spin",
        "times": "Every Thursday.",
        "duration": "All day or timed.",
        "lane": "Offer / SB-adjacent.",
        "cant_with": "Weak as sole peak driver.",
        "variants": "% Bigger; event theme.",
        "extra": "Not deep coin VFM.",
        "examples": _e(
            "2026-05-19 — Golden Spin Full Launch",
            "2026-06-25 — Golden Spin 20% Bigger Multipliers",
            "2026-07-02 — Golden Spin 4th of July theme",
            "2026-08-06 — Golden Spin 30% Bigger Betty Boop",
            "2026-08-13 — Golden Spin",
        ),
    },
    {
        "category": "Purchase & offers",
        "name": "Fortune Dip / Extreme Stamp",
        "times": "Extreme ~2–6/month; Dip on Extreme/sale.",
        "duration": "Dip all day or window; Extreme row = no Config.",
        "lane": "Offer / Extreme Stamp amplifier.",
        "cant_with": "Wild Card; sale days (exceptions documented); second VFM.",
        "variants": "X2 Extreme Stamp; Fortune Dip up to 700% SB.",
        "extra": "RDS→Extreme on Extreme days.",
        "examples": _e(
            "2026-05-07 — X2 Extreme Stamp",
            "2026-08-04 — X2 Extreme Stamp",
            "2026-08-08 — Fortune Dip up to 700% | 14:00–15:00 UTC",
            "2026-07-07 — LBP X2 Extreme Stamps (Night Plan pair)",
            "2026-06-02 — Extreme Stamp day offer stack",
        ),
    },
    {
        "category": "Purchase & offers",
        "name": "Price Cut 20%",
        "times": "2×/month.",
        "duration": "All day.",
        "lane": "Offer.",
        "cant_with": "Second deep VFM; Mondays.",
        "variants": "20% storewide.",
        "extra": "Helps PU.",
        "examples": _e(
            "2026-04-22 — Price Cut 20% storewide",
            "2026-05-14 — Price Cut 20% Coins & offers",
            "2026-06-18 — Price Cut 20%",
            "2026-08-11 — Price Cut 20% Coins & offers | High",
            "2026-07-23 — Price Cut 20%",
        ),
    },
    {
        "category": "Purchase & offers",
        "name": "SlotoBucks / 1st of month denom",
        "times": "1st biggest denom; Bucks 3–6/month.",
        "duration": "Per instance / full day on 1st.",
        "lane": "Offer / SlotoBucks.",
        "cant_with": "MGAP+Bucks weak combo.",
        "variants": "100%–1000% SB contexts.",
        "extra": "RDS/Extreme stamp windows.",
        "examples": _e(
            "2026-08-01 — 1st of month biggest store denom",
            "2026-04-08 — 200% SB guaranteed 2h",
            "2026-05-12 — 300% Extreme Stamp 2h",
            "2026-06-04 — Chance up to 500% SB",
            "2026-07-04 — 700% SB event topper",
        ),
    },
    {
        "category": "Core & gameplay",
        "name": "Core challenges (Win Master / PYP / Spin Zone / Ace Heist / MES)",
        "times": "≥1 coin-sink daily; Spinner ≤1/2 ISO weeks.",
        "duration": "Most of day; some 48h / Night Plan.",
        "lane": "Core · no Gold challenge prize.",
        "cant_with": ">1 gameplay Core/day (Aug Monday); Custom Pod day-1 standalone.",
        "variants": "Win Master · PYP · Spin Zone · Ace Heist · MES · Spinner Clash.",
        "extra": "Spin Zone chase = seasonal headline prize.",
        "examples": _e(
            "2026-04-09 — Win Master new machine 4★ Reg + 4 Hammers",
            "2026-05-02 — Pick your Path Wild Ace",
            "2026-04-17 — Dynamic Spin Zone SNL Dice Wheel",
            "2026-08-08 — Win Master 3★ Reg + 2 Parasheep",
            "2026-08-11 — Ace Heist 4★ Ace card",
        ),
    },
    {
        "category": "Core & gameplay",
        "name": "Custom Pod",
        "times": "Sales/events; 48h.",
        "duration": "Day 1 standalone Core; day 2 not standalone.",
        "lane": "Core / Mid Term (some rows).",
        "cant_with": "Extra Core on day 1 standalone.",
        "variants": "X1000 / X1200 event / X1500 mega.",
        "extra": "Strong forecast lift.",
        "examples": _e(
            "2026-05-12 — Generic Custom Pod x1200",
            "2026-05-22 — Lucy's Custom Pod x1200",
            "2026-06-27 — World Cup Custom Pod",
            "2026-08-01 — Custom Pod X1000",
            "2026-08-07 — Betty Boop Custom Pod x1250",
        ),
    },
    {
        "category": "Gems & amplifiers",
        "name": "Boosted Gemback",
        "times": "Up to ~1/week.",
        "duration": "5 hours · ≥12:00 UTC.",
        "lane": "Gems amplifier.",
        "cant_with": "x2 GGS; Gems Sale same day.",
        "variants": "300% (500% flagship).",
        "extra": "Broad gem halo.",
        "examples": _e(
            "2026-05-16 — Boosted Gemback 300%",
            "2026-05-20 — Boosted Gemback 500% 5 hours",
            "2026-05-10 — Boosted Gemback 500% 00:00–06:00",
            "2026-08-12 — Boosted Gemback 300% (5h post 11:00)",
            "2026-06-08 — Boosted Gemback up to 555%",
        ),
    },
    {
        "category": "Gems & amplifiers",
        "name": "x2 GGS",
        "times": "≤2/week.",
        "duration": "3h post 11:00 UTC.",
        "lane": "Gems · Creative Reuse.",
        "cant_with": "Gems Sale same day.",
        "variants": "Doubles GGS from offers in window.",
        "extra": "Often Tue/Fri.",
        "examples": _e(
            "2026-04-03 — x2 GGS 14:00–18:00",
            "2026-05-10 — x2 GGS 15:00–18:00 UTC",
            "2026-08-04 — x2 GGS (3h post 11:00) | BACKUP",
            "2026-08-07 — x2 GGS 18:00–20:00",
            "2026-08-14 — x2 GGS (3h post 11:00)",
        ),
    },
    {
        "category": "Gems & amplifiers",
        "name": "Gems Sale",
        "times": "≤4/month.",
        "duration": "All day.",
        "lane": "Gems.",
        "cant_with": "x2 GGS same day.",
        "variants": "30% store / 20% offers typical.",
        "extra": "24–48h gem spend follow-up.",
        "examples": _e(
            "2026-05-23 — Gems Sale up to 40%/60% 12h",
            "2026-06-05 — Gems sale up to 40%/60%",
            "2026-07-19 — Gems Sale up to 40%/60%",
            "2026-08-06 — Gems Sale 30% store / 20% offers",
            "2026-08-13 — Gems Sale 30% store / 20% offers",
        ),
    },
    {
        "category": "Dice",
        "name": "Dice Deluxe / Dice Booster",
        "times": "Dice promo ~1.5 weeks; Booster 24h ×3/week.",
        "duration": "Deluxe ~2h post 12:00; Booster 30m–24h.",
        "lane": "Offer (Deluxe) · Booster in offers/Core.",
        "cant_with": "≤1 dice promo/week in builder.",
        "variants": "2 faces / SB / prize wheel / Loot / Dash triggers.",
        "extra": "SNL Dice = seasonal SKU only.",
        "examples": _e(
            "2026-05-20 — Dice Deluxe 2 faces for chance to purchase",
            "2026-05-27 — Dice Deluxe for Prize wheel",
            "2026-06-18 — Dice Deluxe from every side of star dice",
            "2026-08-07 — Dice Deluxe 1×/week | High",
            "2026-08-14 — Dice Deluxe 200% SB Back (starts night plan)",
        ),
    },
    {
        "category": "Clan-Dash & ADS",
        "name": "Clan-Dash / Dash Pass",
        "times": "Monday Dash Day; X2 Badges Wed; X2 Dash Tue+Fri.",
        "duration": "Most of day.",
        "lane": "Clan-Dash · not second VFM.",
        "cant_with": "Heavy revenue promos on Mondays.",
        "variants": "Dash Pass · Bundles · Badge Wheel · Monday Max Deal.",
        "extra": "~11% PU contribution.",
        "examples": _e(
            "2026-04-06 — Monday Max Deal + Time Limited Prize",
            "2026-04-06 — Clan Dash Bundle 30% discount",
            "2026-08-03 — Monday Max Deal + Clan Go Premium",
            "2026-08-10 — Clan Dash Bundle 30% discount",
            "2026-08-04 — x2 Dash Points",
        ),
    },
    {
        "category": "Clan-Dash & ADS",
        "name": "ADS PO",
        "times": "Every day (last in build order).",
        "duration": "All day.",
        "lane": "ADS · low prizes only.",
        "cant_with": "Gold/Shiny/Wild/high Ace; Superboom on ADS.",
        "variants": "Coins · Gems · Reg · Quest Booster · Parasheep · Hero Coins.",
        "extra": "Rotate prize types.",
        "examples": _e(
            "2026-05-02 — ADS PO 2 Blast Picks",
            "2026-05-06 — ADS PO Battlesheep",
            "2026-05-07 — ADS PO Gems",
            "2026-08-05 — ADS PO 2★ Reg card",
            "2026-08-12 — ADS PO 3000 Hero Coins",
        ),
    },
    {
        "category": "Seasonal & album",
        "name": "Shiny Show",
        "times": "3/week; ≥2 days apart; not Monday.",
        "duration": "All day.",
        "lane": "Album (Monday).",
        "cant_with": "Two Shiny same day; Shiny Monday.",
        "variants": "Joker Different / All Cards / Crazy with Aces / + Wolf.",
        "extra": "Gem consumption KPI.",
        "examples": _e(
            "2026-04-01 — Shiny Show Joker All Cards",
            "2026-05-10 — Shiny Show Crazy with Aces",
            "2026-08-04 — Shiny Show Crazy with Aces",
            "2026-08-08 — Shiny Show Joker Different Prizes",
            "2026-08-11 — Shiny Show Joker All Cards",
        ),
    },
    {
        "category": "Seasonal & album",
        "name": "Short Term (Blast / Battlesheep / SNL)",
        "times": "Always ≥1 live · ~5d blocks.",
        "duration": "Season window on Monday row.",
        "lane": "Seasonal / Short Term.",
        "cant_with": "Wrong-season SKU in offers.",
        "variants": "Blast / Battlesheep / SNL prize SKUs.",
        "extra": "Blast > Battlesheep > SNL revenue.",
        "examples": _e(
            "2026-08-01 — Blast Short Term + Blast Wild Ordinary Cozy",
            "2026-08-06 — Battlesheep Wild Gold | Betty Theme",
            "2026-08-11 — SNL Wild Gold",
            "2026-07-01 — Battlesheep wild gold",
            "2026-04-26 — Battlesheep no extra prizes",
        ),
    },
    {
        "category": "Seasonal & album",
        "name": "Mid Term (Winovate / Mega Pods / Quest·Globez·Figz)",
        "times": "Winovate + Mega Pods always on; one rotator.",
        "duration": "Winovate ~8–9d; Mega Pods Mon→Mon.",
        "lane": "Mid Term.",
        "cant_with": "Quest buffer vs Figz/Globez flip.",
        "variants": "Hero Coins · Quest Booster · pod/sticker themes.",
        "extra": "Mega Pods Creative Reuse.",
        "examples": _e(
            "2026-08-03 — Mega Pods Season",
            "2026-08-05 — Winovate Season",
            "2026-08-09 — Globez Season",
            "2026-08-10 — Mega Pods Season",
            "2026-04-12 — Quest Season",
        ),
    },
    {
        "category": "Seasonal & album",
        "name": "Album rhythm",
        "times": "~70d cycle; last week Wild-only purchases.",
        "duration": "Album/Shiny Collection windows.",
        "lane": "Album.",
        "cant_with": "Reg/Ace/Gold purchase prizes final week.",
        "variants": "MS1/MS2 · Shiny Collection · Gold Trading Day.",
        "extra": "Weekly card bank.",
        "examples": _e(
            "2026-08-04 — Album Phase 2 (Shiny MS2)",
            "2026-04-03 — Album Last Day Shiny Collection MS1",
            "2026-05-18 — Album 2nd Shiny Collection Opening",
            "2026-05-01 — Album Starter Pack row",
            "2026-06-20 — Gold Trading Day",
        ),
    },
    {
        "category": "Events, Lotto & Happy Hour",
        "name": "Lotto peak + LBP",
        "times": "Tue+Sat Night Plan peaks.",
        "duration": "LBP 00:00→11:00 UTC calendar day.",
        "lane": "Offer (peak + LBP).",
        "cant_with": "LBP Config filled on peak (leave empty).",
        "variants": "Six-ball rotation; multiballs / themed balls.",
        "extra": "Not second VFM.",
        "examples": _e(
            "2026-08-01 — Lotto peak + LBP 30% Bigger Balls",
            "2026-08-04 — LBP 4 balls instead of 3",
            "2026-08-08 — LBP 2 multiballs",
            "2026-07-04 — LBP 4th of July night plan",
            "2026-07-11 — LBP all gold balls 20% bigger",
        ),
    },
    {
        "category": "Events, Lotto & Happy Hour",
        "name": "Happy Hour / Jumbo Giveaway",
        "times": "Large events.",
        "duration": "Timed ≥12:00.",
        "lane": "HH / Offers.",
        "cant_with": "Amplifier stack without event.",
        "variants": "Jumbo · Prize Picker · themed HH.",
        "extra": "Event cluster ritual.",
        "examples": _e(
            "2026-05-05 — HH Jumbo Giveaway timed",
            "2026-06-04 — Jumbo Giveaway 02:00–03:00 UTC",
            "2026-07-03 — Jumbo 4th of July prizes",
            "2026-04-18 — HH Prize Picker themed",
            "2026-05-28 — HH with SNL dice (SNL week)",
        ),
    },
    {
        "category": "Events, Lotto & Happy Hour",
        "name": "Black Diamond / Event anchors",
        "times": "BD ~1/week; marketing events ad hoc.",
        "duration": "Per row; Event needs Promo Time.",
        "lane": "Black Diamond / Event.",
        "cant_with": "—",
        "variants": "Status Boost · Betty · Nostalgic · Machine open.",
        "extra": "Not second VFM.",
        "examples": _e(
            "2026-08-01 — Status Boost | Event",
            "2026-08-07 — Betty Boop Theme | Event",
            "2026-08-08 — Betty's Birthday MES | Core",
            "2026-08-14 — Nostalgic Weekend | Event",
            "2026-08-14 — Ghost Motel opening | Event",
        ),
    },
    {
        "category": "Other / platform",
        "name": "Popup Store (test)",
        "times": "Per calendar (Aug soft launch).",
        "duration": "Per instance.",
        "lane": "Offer · inner = control SKUs.",
        "cant_with": "Inner SKUs ≠ control Decoy.",
        "variants": "RYD / Buy All / Decoy / Rolling inside shell.",
        "extra": "Suppresses standalone second offer.",
        "examples": _e(
            "2026-08-12 — Popup Store TEST Soft launch (1/3)",
            "2026-08-18 — Popup Store (plan)",
            "2026-08-19 — Popup Store (plan)",
            "2026-07-15 — Popup Store pilot row",
            "2026-06-10 — Popup Store inner Decoy test",
        ),
    },
]

for _entry in GUIDELINES:
    _cat = CATALOG_BY_NAME.get(_entry["name"])
    if _cat:
        _entry["promotion_catalog"] = list(_cat)
