"""Five distinct named promotions per family — for Word field 'What promotions do we have'."""

from __future__ import annotations

CATALOG_BY_NAME: dict[str, tuple[str, str, str, str, str]] = {
    "Daily Deal (DD)": (
        "Daily Deal — 4★ Reg + central SKU | H Pricing",
        "Daily Deal — Wild Ordinary ONCE + separate DD Multiple",
        "Daily Deal — Shiny Limited + PAB hook",
        "Daily Deal — 100% SB + Hammers | H Pricing",
        "Daily Deal — BOGO 2× coins (LiveOps config row)",
    ),
    "RYD (Reveal Your Deal)": (
        "RYD — 100% SB + Hammers Wheel | High",
        "RYD — 100% SB + PAB | High",
        "RYD — Themed 200% SB + Wild Gold | Max",
        "RYD — 3★ Reg + 100% SB | High Price",
        "RYD — 4★ Gold + 100% SB | High Price",
    ),
    "Buy All / Mystery Buy All": (
        "Buy All — Coins + RDS + Reg + seasonal SKU",
        "Buy All — Gems + GGS + Quest Booster",
        "Buy All — AS Wheel + Hammers | H",
        "Buy All — Globez + Hero Coins dual line",
        "Mystery Buy All — hidden prize reveal | H",
    ),
    "Decoy Bonanza": (
        "Decoy Bonanza — d1 Coins + RDS",
        "Decoy Bonanza — d2 Gems + GGS decoy",
        "Decoy Bonanza — d3 5★ Reg + bundle | H",
        "Decoy Bonanza — d3 4★ Gold + bundle | H",
        "Decoy Bonanza — M-H-H tier ladder",
    ),
    "Rolling Offer — Buy X Get Y (BXGY)": (
        "BXGY — Buy 1 Get 8 free steps | H Pricing",
        "BXGY — 2 cycles pay + free ladder | H Pricing",
        "BXGY — 5 cycles supersized (1% / 3% / 5% + 3 Picks)",
        "BXGY — 6 Cycles | M Pricing (Parasheep / AS steps)",
        "BXGY — 6 cycles + milestone bar (Wild / seasonal)",
    ),
    "Rolling Offer — Buy More for Less (BMFL)": (
        "BMFL — 3 cycles tiered %SB + Hammers | High only",
        "BMFL — 3 cycles + 4★ Reg finale | High",
        "BMFL — 3 cycles Parasheep / AS seasonal steps",
        "BMFL — 3 cycles PAB / Wild Any last cycle",
        "BMFL — Monday MFL anchor (no BXGY same day)",
    ),
    "Coin Sale": (
        "Coin Sale — 50 / 75 / 200 / 400% (event themed)",
        "Coin Sale — 100 / 125 / 200 / 555% weekend",
        "Coin Sale — up to 75% / 100% PU tiers",
        "Coin Sale — Betty Boop 50/75/200/400%",
        "Coin Sale — 50/75/200/500% Fri–Sat",
    ),
    "MGAP (BOGO / Bigger / Matched / Wild)": (
        "MGAP BOGO — 100% more + 100% more (2 steps)",
        "MGAP Bigger — boosted coin/gem match",
        "MGAP Matched — paired purchase window",
        "MGAP Wild Symbols — wild hook variant",
        "Extreme MGAP — 200% SB timed window",
    ),
    "Piggy": (
        "Piggy break — 5★ Reg",
        "Piggy break — Shiny card",
        "Piggy break — 5 Hammers",
        "Piggy break — 3★ Reg | High",
        "Piggy break — 4★ Reg | High",
    ),
    "Prize Mania": (
        "Prize Mania — Wild Gold + Dice Booster",
        "Prize Mania — standard Coins/Gems/RDS/GGS/%SB",
        "Prize Mania — 5★ Gold + 200% SB bundle",
        "Prize Mania — 3★ Gold pack | H",
        "Prize Mania — themed Lucy / event skin",
    ),
    "Counter PO": (
        "Counter PO — FTD segmented topper",
        "Counter PO — Night Plan window",
        "Counter PO — on-top high tier",
        "Counter PO — sale-day segmented",
        "Counter PO — post-DD flash window",
    ),
    "Golden Spin": (
        "Golden Spin — Full Launch",
        "Golden Spin — 20% Bigger Multipliers",
        "Golden Spin — event theme (4th of July / Betty)",
        "Golden Spin — 30% Bigger multipliers",
        "Golden Spin — standard Thursday row",
    ),
    "Fortune Dip / Extreme Stamp": (
        "X2 Extreme Stamp — all-day amplifier",
        "Fortune Dip — up to 700% SB timed window",
        "Extreme Stamp — offer stack (DD/PP/Rolling)",
        "LBP pair — X2 Extreme Stamps Night Plan",
        "Sale-day Dip — short window on Extreme row",
    ),
    "Price Cut 20%": (
        "Price Cut 20% — storewide",
        "Price Cut 20% — Coins & offers",
        "Price Cut 20% — mid-week PU helper",
        "Price Cut 20% — Coins & offers | High",
        "Price Cut 20% — no second VFM day",
    ),
    "SlotoBucks / 1st of month denom": (
        "1st of month — biggest store denom row",
        "SlotoBucks — 200% SB guaranteed 2h",
        "SlotoBucks — 300% Extreme Stamp 2h",
        "SlotoBucks — chance up to 500% SB",
        "SlotoBucks — 700% SB event topper",
    ),
    "Core challenges (Win Master / PYP / Spin Zone / Ace Heist / MES)": (
        "Win Master — new machine + Reg + Hammers",
        "Pick your Path — Wild Ace chase",
        "Dynamic Spin Zone — seasonal dice wheel",
        "Ace Heist — Ace card chase",
        "MES / Spinner Clash — event Core row",
    ),
    "Custom Pod": (
        "Custom Pod — Generic x1200",
        "Custom Pod — event x1250 (Betty / sale)",
        "Custom Pod — Lucy's themed x1200",
        "Custom Pod — World Cup x1200",
        "Custom Pod — X1000 sale opener (day 1 standalone)",
    ),
    "Boosted Gemback": (
        "Boosted Gemback — 300% (5h)",
        "Boosted Gemback — 500% flagship (5h)",
        "Boosted Gemback — 500% overnight window",
        "Boosted Gemback — up to 555% promo",
        "Boosted Gemback — post–11:00 UTC 5h block",
    ),
    "x2 GGS": (
        "x2 GGS — 14:00–18:00 UTC",
        "x2 GGS — 15:00–18:00 UTC",
        "x2 GGS — 3h post 11:00 UTC",
        "x2 GGS — 18:00–20:00 event window",
        "x2 GGS — Tue/Fri reuse creative",
    ),
    "Gems Sale": (
        "Gems Sale — 30% store / 20% offers",
        "Gems Sale — up to 40% / 60% 12h",
        "Gems Sale — mid-month gem halo",
        "Gems Sale — post–Core spend follow-up",
        "Gems Sale — no x2 GGS same day",
    ),
    "Dice Deluxe / Dice Booster": (
        "Dice Deluxe — 2 faces purchase chance",
        "Dice Deluxe — Prize wheel hook",
        "Dice Deluxe — star dice all sides",
        "Dice Deluxe — 200% SB Back Night Plan",
        "Dice Booster — 6H / 12H / 24H in offers",
    ),
    "Clan-Dash / Dash Pass": (
        "Monday Max Deal + time-limited prize",
        "Clan Dash Bundle — 30% discount",
        "Clan Go Premium — Dash Pass row",
        "x2 Dash Points — Tue/Fri",
        "x2 Badges — Wednesday",
    ),
    "ADS PO": (
        "ADS PO — 2 Blast Picks",
        "ADS PO — Battlesheep seasonal",
        "ADS PO — Gems",
        "ADS PO — 2★ Reg card",
        "ADS PO — 3000 Hero Coins",
    ),
    "Shiny Show": (
        "Shiny Show — Joker All Cards",
        "Shiny Show — Crazy with Aces",
        "Shiny Show — Joker Different Prizes",
        "Shiny Show — Crazy with Aces + Wolf",
        "Shiny Show — album gem-sink variant",
    ),
    "Short Term (Blast / Battlesheep / SNL)": (
        "Short Term — Blast + Wild Ordinary Cozy",
        "Short Term — Battlesheep Wild Gold",
        "Short Term — SNL Wild Gold / Dice SKUs",
        "Short Term — Blast picks / stickers",
        "Short Term — Battlesheep no-extra-prizes week",
    ),
    "Mid Term (Winovate / Mega Pods / Quest·Globez·Figz)": (
        "Mega Pods Season — Mon→Mon window",
        "Winovate Season — ~8–9 day block",
        "Quest Season — rotator slot",
        "Globez Season — rotator slot",
        "Figz Season — rotator slot",
    ),
    "Album rhythm": (
        "Album — Phase 2 Shiny MS2",
        "Album — Last Day Shiny Collection MS1",
        "Album — 2nd Shiny Collection opening",
        "Album — Starter Pack row",
        "Gold Trading Day — Wild-only purchases",
    ),
    "Lotto peak + LBP": (
        "Lotto peak + LBP — 30% Bigger Balls",
        "LBP — 4 balls instead of 3",
        "LBP — 2 multiballs",
        "LBP — 4th of July night plan",
        "LBP — all gold balls 20% bigger",
    ),
    "Happy Hour / Jumbo Giveaway": (
        "Happy Hour — Jumbo Giveaway timed",
        "Jumbo Giveaway — 02:00–03:00 UTC",
        "Jumbo — 4th of July prize mix",
        "Happy Hour — Prize Picker themed",
        "Happy Hour — SNL dice week skin",
    ),
    "Black Diamond / Event anchors": (
        "Status Boost — Event row",
        "Betty Boop Theme — Event",
        "Nostalgic Weekend — Event",
        "Ghost Motel machine opening — Event",
        "Betty's Birthday — MES / Core tie-in",
    ),
    "Popup Store (test)": (
        "Popup Store — Soft launch TEST (1/3)",
        "Popup Store — inner RYD shell",
        "Popup Store — inner Buy All shell",
        "Popup Store — inner Decoy shell",
        "Popup Store — inner Rolling shell",
    ),
}
