#!/usr/bin/env python3
"""Dry-run-first writer for reviewed Operation - Monetization task specs.

Creates/updates subitems under an exact YYYY-MM-DD parent. Never deletes.
"""

from __future__ import annotations

import argparse
import json
import re
import time
from pathlib import Path
from typing import Any

from monday_client import gql

ROOT = Path(__file__).resolve().parents[1]
BOARD_ID = "2109172490"
SUBITEM_BOARD_ID = "2109172677"
DAY_GROUP_ID = "group_mm0t6mxh"
AUTOMATION_SETTLE_SECONDS = 7


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("spec", type=Path, help="Reviewed JSON generated by build_ops_tasks_from_plan.py")
    parser.add_argument("--commit", action="store_true", help="Write proposed changes to Monday")
    parser.add_argument(
        "--create-day",
        action="store_true",
        help="Allow creation of a missing day parent (requires --commit)",
    )
    parser.add_argument(
        "--update-existing",
        action="store_true",
        help="Allow updating same-name subitems (otherwise existing tasks are skipped)",
    )
    parser.add_argument(
        "--allow-tbd",
        action="store_true",
        help="Allow live write with unresolved TBD/requires_review fields",
    )
    parser.add_argument(
        "--description-only",
        action="store_true",
        help="Update only long_text on existing matched tasks; never create or rename",
    )
    parser.add_argument(
        "--replace-day",
        action="store_true",
        help="Delete all existing subitems under the day parent, then create from spec (requires --commit)",
    )
    parser.add_argument(
        "--parent-id",
        type=str,
        default="",
        help="Ops day parent pulse id (e.g. Buy All YYYY-MM-DD row); skips Monday-days name lookup",
    )
    return parser.parse_args()


def normalized_name(value: str) -> str:
    value = value.replace("—", "-").replace("–", "-").lower()
    return re.sub(r"\s+", " ", value).strip()


def validate_spec(spec: dict[str, Any], *, allow_tbd: bool) -> None:
    if str(spec.get("board_id")) != BOARD_ID:
        raise SystemExit(f"Refusing board {spec.get('board_id')}; expected {BOARD_ID}")
    day = spec.get("parent_day")
    if not isinstance(day, str) or not re.fullmatch(r"\d{4}-\d{2}-\d{2}", day):
        raise SystemExit("Spec parent_day must be YYYY-MM-DD")
    if not spec.get("tasks"):
        raise SystemExit("Spec contains no tasks")
    unresolved: list[str] = []
    for task in spec["tasks"]:
        for field in ("task_name", "start_date", "end_date", "description", "m_and_m_status"):
            if not task.get(field):
                raise SystemExit(f"Task missing required field {field}: {task.get('task_name')}")
        if task.get("parent_day") != day:
            raise SystemExit(f"Task parent {task.get('parent_day')} differs from spec parent {day}")
        if task.get("requires_review") or "TBD - owner required" in task["description"]:
            unresolved.append(task["task_name"])
        if task.get("reuse") is None:
            unresolved.append(f"{task['task_name']} (reuse not verified)")
        if task.get("reuse") is True and not task.get("recent_ops_reference"):
            unresolved.append(f"{task['task_name']} (reuse source missing)")
    if unresolved and not allow_tbd:
        joined = ", ".join(unresolved)
        raise SystemExit(
            "Live write blocked: unresolved review/TBD fields in "
            f"{joined}. Review the spec, or explicitly pass --allow-tbd."
        )


def fetch_day_parent(day: str) -> dict[str, Any] | None:
    query = """
    query {
      boards(ids: [2109172490]) {
        groups(ids: ["group_mm0t6mxh"]) {
          items_page(limit: 500) {
            items {
              id name
              subitems {
                id name
                column_values(ids: ["board_relation_mkzvrve9"]) {
                  ... on BoardRelationValue { linked_items { id } }
                }
              }
            }
          }
        }
      }
    }
    """
    data = gql(query)
    groups = data["boards"][0]["groups"]
    items = groups[0]["items_page"]["items"] if groups else []
    return next((item for item in items if item["name"].strip() == day), None)


def fetch_parent_by_id(item_id: str) -> dict[str, Any] | None:
    query = """
    query ($id: ID!) {
      items(ids: [$id]) {
        id name
        subitems {
          id name
          column_values(ids: ["board_relation_mkzvrve9"]) {
            ... on BoardRelationValue { linked_items { id } }
          }
        }
      }
    }
    """
    items = gql(query, {"id": item_id})["items"]
    return items[0] if items else None


def create_day_parent(day: str) -> dict[str, Any]:
    query = """
    mutation ($board: ID!, $group: String!, $name: String!) {
      create_item(board_id: $board, group_id: $group, item_name: $name) { id name }
    }
    """
    parent = gql(query, {"board": BOARD_ID, "group": DAY_GROUP_ID, "name": day})["create_item"]
    set_columns(
        board_id=BOARD_ID,
        item_id=parent["id"],
        values={"date4": {"date": day}},
    )
    parent["subitems"] = []
    return parent


def create_subitem(parent_id: str, name: str) -> str:
    query = """
    mutation ($parent: ID!, $name: String!) {
      create_subitem(parent_item_id: $parent, item_name: $name) { id }
    }
    """
    return gql(query, {"parent": parent_id, "name": name})["create_subitem"]["id"]


def set_columns(*, board_id: str, item_id: str, values: dict[str, Any]) -> None:
    query = """
    mutation ($board: ID!, $item: ID!, $values: JSON!) {
      change_multiple_column_values(
        board_id: $board,
        item_id: $item,
        column_values: $values
      ) { id }
    }
    """
    gql(
        query,
        {
            "board": board_id,
            "item": item_id,
            "values": json.dumps(values, ensure_ascii=False),
        },
    )


def delete_subitem(item_id: str) -> None:
    query = """
    mutation ($item: ID!) {
      delete_item(item_id: $item) { id }
    }
    """
    gql(query, {"item": item_id})


def rename_subitem(item_id: str, name: str) -> None:
    query = """
    mutation ($board: ID!, $item: ID!, $name: String!) {
      change_simple_column_value(
        board_id: $board,
        item_id: $item,
        column_id: "name",
        value: $name
      ) { id }
    }
    """
    gql(query, {"board": SUBITEM_BOARD_ID, "item": item_id, "name": name})


def column_values(task: dict[str, Any]) -> dict[str, Any]:
    values: dict[str, Any] = {
        "date_mm0f8tdb": {
            "date": task.get("monday_start_date") or task["start_date"],
            "time": task.get("monday_start_time") or task.get("start_time") or "11:00:00",
        },
        "date_mm0fr8sp": {
            "date": task.get("monday_end_date") or task["end_date"],
            "time": task.get("monday_end_time") or task.get("end_time") or "11:00:00",
        },
        "long_text": {"text": task["description"]},
        "status": {"label": task["m_and_m_status"]},
    }
    if "times_per_player" in task:
        label = task.get("times_per_player")
        if label:
            values["times_per_player__1"] = {"labels": [label]}
        else:
            values["times_per_player__1"] = {"labels": []}
    if task.get("due_date"):
        values["date_mkp4d99c"] = {"date": task["due_date"]}
    if task.get("source_mm_item_id"):
        values["board_relation_mkzvrve9"] = {
            "item_ids": [int(task["source_mm_item_id"])]
        }
    return values


def print_dry_run(spec: dict[str, Any], parent: dict[str, Any] | None) -> None:
    print(f"DRY RUN - board {BOARD_ID}, day {spec['parent_day']}")
    print(f"Parent: {'found ' + parent['id'] if parent else 'MISSING (no write)'}")
    existing = {
        normalized_name(item["name"]): item for item in (parent or {}).get("subitems", [])
    }
    existing_by_source: dict[str, dict[str, Any]] = {}
    for item in (parent or {}).get("subitems", []):
        for column in item.get("column_values") or []:
            for linked in column.get("linked_items") or []:
                existing_by_source[str(linked["id"])] = item
    for index, task in enumerate(spec["tasks"], start=1):
        match = existing.get(normalized_name(task["task_name"]))
        if not match and task.get("source_mm_item_id"):
            match = existing_by_source.get(str(task["source_mm_item_id"]))
        if not match and task.get("source_row_name"):
            match = existing.get(normalized_name(task["source_row_name"]))
        action = "UPDATE" if match else "CREATE"
        print(
            f"\n[{index}/{len(spec['tasks'])}] {action}: {task['task_name']}"
            f"\n  M&M Status: {task['m_and_m_status']}"
            f"\n  Window: {task['start_at']} -> {task['end_at']}"
            f"\n  Due: {task.get('due_date') or 'not set'}"
            f"\n  Review: {task.get('requires_review', False)}"
            f"\n  Reuse: {task.get('reuse')}"
            f"\n  Recent Ops reference: {task.get('recent_ops_reference') or 'not resolved'}"
        )
        for warning in task.get("warnings") or []:
            print(f"  WARNING: {warning}")
        print("  Description:")
        for line in task["description"].splitlines():
            print(f"    {line}")
    print("\nNo Monday changes were made.")


def commit(spec: dict[str, Any], parent: dict[str, Any] | None, args: argparse.Namespace) -> None:
    if parent is None:
        if not args.create_day:
            raise SystemExit(
                f"Day parent {spec['parent_day']} is missing. "
                "Create it through the normal board process or explicitly pass --create-day."
            )
        parent = create_day_parent(spec["parent_day"])
        print(f"Created day parent {spec['parent_day']} ({parent['id']})")
    deleted = 0
    if args.replace_day:
        if args.description_only:
            raise SystemExit("--replace-day cannot be used with --description-only")
        for sub in list(parent.get("subitems") or []):
            delete_subitem(sub["id"])
            deleted += 1
            print(f"DELETED: {sub['name']} ({sub['id']})")
        parent["subitems"] = []
    existing = {
        normalized_name(item["name"]): item for item in parent.get("subitems", [])
    }
    existing_by_source: dict[str, dict[str, Any]] = {}
    for item in parent.get("subitems", []):
        for column in item.get("column_values") or []:
            for linked in column.get("linked_items") or []:
                existing_by_source[str(linked["id"])] = item

    def match_existing(task: dict[str, Any]) -> dict[str, Any] | None:
        hit = existing.get(normalized_name(task["task_name"]))
        if hit:
            return hit
        source_id = str(task.get("source_mm_item_id") or "")
        if source_id and source_id in existing_by_source:
            return existing_by_source[source_id]
        source_row = task.get("source_row_name") or ""
        if source_row:
            return existing.get(normalized_name(source_row))
        return None

    created = updated = skipped = 0
    for task in spec["tasks"]:
        match = match_existing(task)
        if args.description_only:
            if not match:
                raise SystemExit(
                    f"Description-only update requires existing task: {task['task_name']}"
                )
            set_columns(
                board_id=SUBITEM_BOARD_ID,
                item_id=match["id"],
                values={"long_text": {"text": task["description"]}},
            )
            updated += 1
            print(f"UPDATED DESCRIPTION: {task['task_name']} ({match['id']})")
            continue
        if match and not args.update_existing:
            print(f"SKIP existing: {task['task_name']} ({match['id']})")
            skipped += 1
            continue
        if match:
            item_id = match["id"]
            rename_subitem(item_id, task["task_name"])
            updated += 1
            action = "UPDATED"
            is_new = False
        else:
            item_id = create_subitem(parent["id"], task["task_name"])
            created += 1
            action = "CREATED"
            is_new = True
        set_columns(
            board_id=SUBITEM_BOARD_ID,
            item_id=item_id,
            values=column_values(task),
        )
        if is_new:
            time.sleep(AUTOMATION_SETTLE_SECONDS)
            set_columns(
                board_id=SUBITEM_BOARD_ID,
                item_id=item_id,
                values=column_values(task),
            )
        print(f"{action}: {task['task_name']} ({item_id})")
        existing[normalized_name(task["task_name"])] = {"id": item_id, "name": task["task_name"]}
    print(f"Done: created {created}, updated {updated}, skipped {skipped}; deleted {deleted}.")


def main() -> None:
    args = parse_args()
    if args.create_day and not args.commit:
        raise SystemExit("--create-day is valid only with --commit")
    if args.description_only and (not args.commit or not args.update_existing):
        raise SystemExit("--description-only requires --commit --update-existing")
    if args.replace_day and args.update_existing:
        raise SystemExit("--replace-day creates fresh subitems; do not pass --update-existing")
    spec = json.loads(args.spec.read_text(encoding="utf-8"))
    if args.parent_id:
        parent = fetch_parent_by_id(args.parent_id.strip())
        if parent is None:
            raise SystemExit(f"Parent item {args.parent_id} not found")
    else:
        parent = fetch_day_parent(spec.get("parent_day") or "")
    if not args.commit:
        print_dry_run(spec, parent)
        return
    validate_spec(spec, allow_tbd=args.allow_tbd)
    commit(spec, parent, args)


if __name__ == "__main__":
    main()
